/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostRouteImport } from './routes/host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as HostTripRouteImport } from './routes/host.trip'
import { Route as HostTodosRouteImport } from './routes/host.todos'
import { Route as HostRequestsRouteImport } from './routes/host.requests'
import { Route as HostQuestionRouteImport } from './routes/host.question'
import { Route as HostAvailabilityRouteImport } from './routes/host.availability'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const HostTripRoute = HostTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => HostRoute,
} as any)
const HostTodosRoute = HostTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => HostRoute,
} as any)
const HostRequestsRoute = HostRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => HostRoute,
} as any)
const HostQuestionRoute = HostQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => HostRoute,
} as any)
const HostAvailabilityRoute = HostAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => HostRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/availability': typeof HostAvailabilityRoute
  '/host/question': typeof HostQuestionRoute
  '/host/requests': typeof HostRequestsRoute
  '/host/todos': typeof HostTodosRoute
  '/host/trip': typeof HostTripRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/host/availability': typeof HostAvailabilityRoute
  '/host/question': typeof HostQuestionRoute
  '/host/requests': typeof HostRequestsRoute
  '/host/todos': typeof HostTodosRoute
  '/host/trip': typeof HostTripRoute
  '/host': typeof HostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/availability': typeof HostAvailabilityRoute
  '/host/question': typeof HostQuestionRoute
  '/host/requests': typeof HostRequestsRoute
  '/host/todos': typeof HostTodosRoute
  '/host/trip': typeof HostTripRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/login'
    | '/host/availability'
    | '/host/question'
    | '/host/requests'
    | '/host/todos'
    | '/host/trip'
    | '/host/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/host/availability'
    | '/host/question'
    | '/host/requests'
    | '/host/todos'
    | '/host/trip'
    | '/host'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/login'
    | '/host/availability'
    | '/host/question'
    | '/host/requests'
    | '/host/todos'
    | '/host/trip'
    | '/host/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/trip': {
      id: '/host/trip'
      path: '/trip'
      fullPath: '/host/trip'
      preLoaderRoute: typeof HostTripRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/todos': {
      id: '/host/todos'
      path: '/todos'
      fullPath: '/host/todos'
      preLoaderRoute: typeof HostTodosRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/requests': {
      id: '/host/requests'
      path: '/requests'
      fullPath: '/host/requests'
      preLoaderRoute: typeof HostRequestsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/question': {
      id: '/host/question'
      path: '/question'
      fullPath: '/host/question'
      preLoaderRoute: typeof HostQuestionRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/availability': {
      id: '/host/availability'
      path: '/availability'
      fullPath: '/host/availability'
      preLoaderRoute: typeof HostAvailabilityRouteImport
      parentRoute: typeof HostRoute
    }
  }
}

interface HostRouteChildren {
  HostAvailabilityRoute: typeof HostAvailabilityRoute
  HostQuestionRoute: typeof HostQuestionRoute
  HostRequestsRoute: typeof HostRequestsRoute
  HostTodosRoute: typeof HostTodosRoute
  HostTripRoute: typeof HostTripRoute
  HostIndexRoute: typeof HostIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostAvailabilityRoute: HostAvailabilityRoute,
  HostQuestionRoute: HostQuestionRoute,
  HostRequestsRoute: HostRequestsRoute,
  HostTodosRoute: HostTodosRoute,
  HostTripRoute: HostTripRoute,
  HostIndexRoute: HostIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
